// <auto-generated />
using System;
using DiplomaDBL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiplomaDBL.Migrations
{
    [DbContext(typeof(DiplomaDbContext))]
    [Migration("20200517194829_initialsecond")]
    partial class initialsecond
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiplomaEntities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Гриби"
                        });
                });

            modelBuilder.Entity("DiplomaEntities.Models.FoodInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameToDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QualityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QualityId");

                    b.ToTable("FoodInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Характерною ознакою роду печериць від інших печерицевих є колір пластинок: від рожевуватих у молодих плодових тіл, до темно-коричневих у зрілих грибів, темно-коричневим, бурувато-чорним споровим порошком та прирослим до ніжки кільцем. Шапинка куляста, конусовидна або дзвониковидна, м'ясиста, щільна, поврехня гладка, луската, білувата, рідше коричнювата. Пластинки вільні, тонкі, вузькі, при дозріванні розпливаються. Ніжка зазвичай центральна, рівна, щільна.",
                            NameToDisplay = "Печериця",
                            OfficialName = "Agarius",
                            QualityId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Шапка 5-12(20) см у діаметрі, напівсферична, згодом опукло-тугого плоска, з тонким рубчастим краєм, цегляно-червона різних відтінків, жовто-червона, червоно-помаранчева, з численними білими пластівцями, які іноді зникають після дощу . Пластинки густі, тонкі, білі. Спорова маса біла. Спори 9-11 Х 6-8 мкм, широкоовальні. Ніжка 5-13 × 1-3 см, циліндрична, з великою бульбою, щільна, пізніше з порожниною, гола з широким білим (по краю жовтим) кільцем, з прирослою у вигляді концентричних, бородавчастолускатих смуг піхвою. М'якуш білий, у периферичному шарі тканини шапки жовтуватий без особливого запаху. Отруйний гриб.",
                            NameToDisplay = "Мухомор",
                            OfficialName = "Amanita",
                            QualityId = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Плодове тіло цих грибів велике, м'ясисте. Ніжка товста, особливо у молодих грибів, з характерним рельєфним малюнком, рідше ворсиста або гладка.",
                            NameToDisplay = "Білий гриб",
                            OfficialName = "Boletus",
                            QualityId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Шапка 3-8 см у діаметрі, тупоконусоподібна, з жовтою кортиною, згодом опуклорозпростерта, з тупим горбом у центрі, з опущеним, тріщинуватим краєм, руда, оранжево-руда, цегляно-коричнювата, у центрі темніша, тонкоповстиста, темноволокнисто-луската. Пластинки рідкі, широкі, оранжуваті, потім червонувато-руді. Спорова маса іржаво-коричнева. Спори 8,5-11 Х 5,5-7,7 мкм, еліпсоподібні, дрібнобородавчасті. Ніжка 3-9 Х 0,4-1,5 см, часто До основи трохи звужується і переходить у коренеподібний виріст, щільна, золотисто-жовта (або вохряна), внизу руда-коричнева, гола. М'якуш у шапці червонувато-коричнюватий, у ніжці жовтий, трохи пахне редькою. Розчин соди забарвлює шкірку шапки та ніжки у чорний колір. В Україні поширений у західному Поліссі.Росте у листяних та хвойних лісах у вересні — жовтні. Дуже небезпечний отруйний гриб.Містить токсин ореланін.Спричиняє тяжке, іноді смертельне отруєння.",
                            NameToDisplay = "Павутинник",
                            OfficialName = "Cortinarius",
                            QualityId = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Шапка 4—10(11) см у діаметрі, опукло-, плоско- або увігнуторозпростерта, часом з горбом, сріблясто-сіра, оливкувато- або іноді жовтувато-сіра, при зволоженні темніє, при підсиханні світлішає, гола, блискуча. Пластинки прирослі, іноді злегка переходять на ніжку, білі, рожеві. Спори 8—10,5 X 7—8 мкм, кутасто-кулясті або кутасто-широкоовальні. Ніжка 5—11 X 0,5—1,5 см, щільна, з віком порожня, біла, згодом сірувата, гола. М'якуш щільний, білий, спочатку пахне борошном, при підсиханні з неприємним запахом. В Україні поширений у Прикарпатті, на Поліссі та в Лісостепу.Росте у листяних(дубових, букових) лісах; часто; у серпні — вересні. Отруйний гриб.",
                            NameToDisplay = "Ентолома",
                            OfficialName = "Entoloma",
                            QualityId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Капелюшок ∅ 0,5-12 см, конічна, колокольчатая або полушаровидная, потім розпростерта, іноді з горбком або вдавлені в центрі, гладка або луската, волокниста, суха, волога або слизова, зазвичай яскраво забарвлені, червона, оранжево-жовта, іноді темніють або чорніючий з віком. Платівки приросли або низхідні, товсті, рідкісні, від білих до яркоокрашенних - червоні, рожеві, жовті.Ніжка циліндрична, часто звужена до основи, суха або клейка, гладка або волокниста, часто перекручена, одноколірна з капелюшком, порожниста. Споровий порошок білого кольору.",
                            NameToDisplay = "Вологоголовка",
                            OfficialName = "Hygrocybe",
                            QualityId = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Шапка 3-10(12) см у діаметрі, м'ясиста, увігнута, іноді майже лійкоподібна, сірувато-оранжево-руда, з темнішими, більш або менш виразними концентричними смугами, гола, клейкувата. Пластинки оранжево-жовті або вохряні, від дотику зеленіють. Спори 7-9 Х 6-7 мкм, бородавчасті. Ніжка кольору шапки або світліша, 3-7 Х 1-2,5 см, щільна, згодом з порожниною. М'якуш у шапці жовтий, у ніжці білий (всередині), у периферичній частині шапки та особливо ніжки оранжево-червоний, при розрізуванні на повітрі поволі зеленіє. Молочний сік оранжево-червоний, з приємним (гоструватим) смаком і запахом, на повітрі не змінюється (лише через кілька годин стає сіро-зеленим).",
                            NameToDisplay = "Рижик",
                            OfficialName = "Lactarius",
                            QualityId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Шапинка їх опукло-плеската або ввігнуто-розпроста, яскраво забарвлена, м'якуш крихкий, солодкий або пекучоїдкий. В Україні — бл. 50 видів, їстівні.Ростуть у мішаних, рідше в шпилькових(хвойних) лісах.Найпоширеніші: Сироїжка біла(R.delica Fr.) і Сироїжка їстівна(R.vesca L.).Сироїжки становлять не менш однієї третини врожаю всіх їстівних грибів.",
                            NameToDisplay = "Сироїжка",
                            OfficialName = "Russula",
                            QualityId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Шапка 3-8 (10-12) см у діаметрі, брудно-рожевуватокоричнювата, червонувато- або жовтувата-коричнювата, здебільшого нерівно забарвлена, до краю світліша, гола, клейкувата, при підсиханні блискуча. Шкірка знімається. Пори великі, кутасті, з нерівними краями, сірувато.-жовті, згодом зеленуватожовті, пізніше оливкувато-коричневі. Спори жовтуваті, 6-10 Х 3-4 мкм. Ніжка 4-8 Х 1-2 см, часто зігнута, щільна, кольору шапки або світліша, донизу здебільшого червонувато. М'якуш щільний, жовтувата-червонувато-коричнюватий, при розрізуванні на повітрі не змінюється, без особливого запаху.",
                            NameToDisplay = "Маслюк",
                            OfficialName = "Suillus",
                            QualityId = 1
                        });
                });

            modelBuilder.Entity("DiplomaEntities.Models.Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Qualitys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Можна споживати"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Можна споживати за умови правильної обробки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Не можна споживати"
                        });
                });

            modelBuilder.Entity("DiplomaEntities.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodInfoId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenOccured")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoodInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("DiplomaEntities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiplomaEntities.Models.FoodInfo", b =>
                {
                    b.HasOne("DiplomaEntities.Models.Category", "Category")
                        .WithMany("FoodInfos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaEntities.Models.Quality", "Quality")
                        .WithMany("FoodInfos")
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomaEntities.Models.Request", b =>
                {
                    b.HasOne("DiplomaEntities.Models.FoodInfo", "FoodInfo")
                        .WithMany("Requests")
                        .HasForeignKey("FoodInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaEntities.Models.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
